name = "yawpr"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[vars]
APP_URL = "https://yawpr.dev"

[[d1_databases]]
binding = "DB"
database_name = "yawpr-db"
database_id = "a3d97918-4813-4f31-bc84-424091b4ebec"
migrations_dir = "src/db/migrations"

[[queues.producers]]
binding = "NOTIFICATION_QUEUE"
queue = "yawpr-notifications"

[[queues.consumers]]
queue = "yawpr-notifications"
max_batch_size = 10
max_retries = 3

[assets]
directory = "public"
